org:
  springframework:
    boot:
      autoconfigure:
        EnableAutoConfiguration: org.ditto.easyhan.config.SpringConfig
security:
  basic:
    enabled:
      false
management:
  security:
    enabled: false
grpc:
  port: 8980
server:
  port: 8088
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL5Dialect
  data:
    jpa:
      repositories:
        enabled: true
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: druid
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 下面的3个参数在production中可以适当调整,使用相同key可以覆盖即可
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 5
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters:
        - stat
        - wall
        - log4j
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        session-stat-enable: true
        session-stat-max-count: 1000
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
          enabled: true
          reset-enable: true
          login-username: druid
          login-password: druid
          allow: 127.0.0.1
      # 配置StatFilter
      filter:
          stat:
            db-type: mysql
            log-slow-sql: true
            slow-sql-millis: 1000
      # 配置WallFilter
          wall:
              enabled: true
              db-type: mysql
              config:
                delete-allow: false
                drop-table-allow: false
    