# pro环境
spring:
  datasource:
    url: jdbc:mysql://rm-bp155px1rbia7zvl6.mysql.rds.aliyuncs.com:3306/gedit_store?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: qzd
    password: QZD1qaz2wsx
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 60000